server:
  port: 3306

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: mysql://root:sfLzOExDaeXCFHWUGQLmrbVOOQfTCwVW@mysql.railway.internal:3306/railway
    username: root
    password: sfLzOExDaeXCFHWUGQLmrbVOOQfTCwVW
  servlet:
    multipart:
      max-request-size: 10MB
      max-file-size: 20MB
      location: d:/upload/

mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true

